// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tprrdgoznrbyxhftwfgl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRwcnJkZ296bnJieXhoZnR3ZmdsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2NTgzNDcsImV4cCI6MjA2NDIzNDM0N30.YESTwiubK2xdSZqp9V2zFzUPJgDFZzKVoa62mNj4HH8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);